// <auto-generated />
namespace UsersApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class NewEmployeeId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewEmployeeId));
        
        string IMigrationMetadata.Id
        {
            get { return "202506230538032_NewEmployeeId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
